package instance

const (
	Name     = "exoscale_compute_instance"
	NameList = "exoscale_compute_instance_list"

	AttrAntiAffinityGroupIDs = "anti_affinity_group_ids"
	AttrCreatedAt            = "created_at"
	AttrDeployTargetID       = "deploy_target_id"
	AttrDiskSize             = "disk_size"
	AttrElasticIPIDs         = "elastic_ip_ids"
	AttrID                   = "id"
	AttrIPv6                 = "ipv6"
	AttrIPv6Address          = "ipv6_address"
	AttrLabels               = "labels"
	AttrManagerID            = "manager_id"
	AttrManagerType          = "manager_type"
	AttrName                 = "name"
	AttrNetworkInterface     = "network_interface"
	AttrPrivateNetworkIDs    = "private_network_ids"
	AttrPublicIPAddress      = "public_ip_address"
	AttrPrivate              = "private"
	AttrReverseDNS           = "reverse_dns"
	AttrSSHKey               = "ssh_key"
	AttrSecurityGroupIDs     = "security_group_ids"
	AttrState                = "state"
	AttrTemplateID           = "template_id"
	AttrType                 = "type"
	AttrUserData             = "user_data"
	AttrZone                 = "zone"
)
