#cloud-config
---
manage_etc_hosts: true

write_files:
- path: /etc/netplan/01-privnet.yaml
  content: |
    network:
      version: 2
      renderer: networkd
      ethernets:
        eth1:
          dhcp4: true

runcmd:
- ["netplan", "apply"]
