name: check-documentation

on:
  push:
    branches:
    - '**'
    paths-ignore:
    - '.github/ISSUE_TEMPLATE/*'
    - '.github/*.md'
    tags-ignore:
    - 'v*' # Don't run CI tests on release tags

jobs:
  check-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git submodule update --init --recursive go.mk
      - uses: ./go.mk/.github/actions/setup
      - name: Check documentation is up to date
        run: './scripts/check-documentation-clean.sh'
