---
name: run-acceptance-tests

on:
  workflow_dispatch:
    inputs:
      go_test_extra_args:
        description: 'Extra arguments to pass to Go tests (e.g. -run="^Test(?!.*(Database|SOS)).*")'
        required: false
        type: string
        default: ''
  push:
    branches:
    - '**'
    paths:
    - 'go.mod'
    - 'go.sum'
    - '**.go'
    - '.github/workflows/tests.yml'
    tags-ignore:
    - 'v*' # Don't run CI tests on release tags

# Prevent // execution of acc tests
concurrency: acc-tests

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: make go.mk
      - uses: ./go.mk/.github/actions/setup
      - uses: ./go.mk/.github/actions/pre-check
      - name: Run tests with default arguments
        if: github.event.inputs.go_test_extra_args == ''
        run: |
          echo "Running with default arguments"
          make test-verbose test-acc
        env:
          EXOSCALE_API_KEY: ${{ secrets.EXOSCALE_API_KEY }}
          EXOSCALE_API_SECRET: ${{ secrets.EXOSCALE_API_SECRET }}
      - name: Run tests with custom arguments
        if: github.event.inputs.go_test_extra_args != ''
        run: |
          echo "Input args: '${{ github.event.inputs.go_test_extra_args }}'"
          # Debug environment before setting
          echo "Environment vars before:"
          env | grep GO_TEST

          # Set environment variable
          export GO_TEST_EXTRA_ARGS="${{ github.event.inputs.go_test_extra_args }}"

          # Debug environment after setting
          echo "Environment vars after:"
          env | grep GO_TEST

          # Print make variables to see what make sees
          echo "Make sees:"
          make -pn | grep GO_TEST_EXTRA_ARGS

          # Run the actual command
          make test-verbose test-acc
        env:
          EXOSCALE_API_KEY: ${{ secrets.EXOSCALE_API_KEY }}
          EXOSCALE_API_SECRET: ${{ secrets.EXOSCALE_API_SECRET }}
          GO_TEST_EXTRA_ARGS: ${{ github.event.inputs.go_test_extra_args }}
